import { describe, expect, it, vi } from "vitest";
import { buildFailedTransactionFromDirectError } from "../src/direct.js";

vi.mock("../src/xdr.js", () => ({
  deepDecodeXdr: (value: unknown) => value,
}));

const submission = {
  kind: "rpc_simulate" as const,
  transactionXdr:
    "AAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGQAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAABp1o9lAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAABzXrHlDVNUPOxhsf77xASbfB/2k8LjWHIuCtc+U6tcSwAAAAHZXhlY3V0ZQAAAAADAAAAEgAAAAHXkotywnA8z+r365/0701QSlWouXn8m0UOoshCtNHOYQAAAA8AAAAIdHJhbnNmZXIAAAAQAAAAAQAAAAMAAAASAAAAAc16x5Q1TVDzsYbH++8QEm3wf9pPC41hyLgrXPlOrXEsAAAAEgAAAAGZH28E7P7H2iQu3i7ds5muWQeGxQ1ET69x36oYUvdmFAAAAAoAAAAAAAAAAAAAAAAF9eEAAAAAAAAAAAAAAAAA",
  response: {
    error:
      "HostError: Error(Contract, #10)\n\nEvent log (newest first):\n   0: [Diagnostic Event] contract:CDGXVR4UGVGVB45RQ3D7X3YQCJW7A762J4FY2YOIXAVVZ6KOVVYSYBX5, topics:[error, Error(Contract, #10)], data:\"escalating error to VM trap from failed host function call: call\"\n   1: [Diagnostic Event] contract:CDGXVR4UGVGVB45RQ3D7X3YQCJW7A762J4FY2YOIXAVVZ6KOVVYSYBX5, topics:[error, Error(Contract, #10)], data:[\"contract call failed\", transfer, [CDGXVR4UGVGVB45RQ3D7X3YQCJW7A762J4FY2YOIXAVVZ6KOVVYSYBX5, CCMR63YE5T7MPWREF3PC5XNTTGXFSB4GYUGUIT5POHP2UGCS65TBIUUU, 100000000]]\n   2: [Failed Diagnostic Event (not emitted)] contract:CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC, topics:[error, Error(Contract, #10)], data:[\"zero balance is not sufficient to spend\", 100000000]\n   3: [Diagnostic Event] contract:CDGXVR4UGVGVB45RQ3D7X3YQCJW7A762J4FY2YOIXAVVZ6KOVVYSYBX5, topics:[fn_call, CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC, transfer], data:[CDGXVR4UGVGVB45RQ3D7X3YQCJW7A762J4FY2YOIXAVVZ6KOVVYSYBX5, CCMR63YE5T7MPWREF3PC5XNTTGXFSB4GYUGUIT5POHP2UGCS65TBIUUU, 100000000]\n   4: [Diagnostic Event] topics:[fn_call, CDGXVR4UGVGVB45RQ3D7X3YQCJW7A762J4FY2YOIXAVVZ6KOVVYSYBX5, execute], data:[CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC, transfer, [CDGXVR4UGVGVB45RQ3D7X3YQCJW7A762J4FY2YOIXAVVZ6KOVVYSYBX5, CCMR63YE5T7MPWREF3PC5XNTTGXFSB4GYUGUIT5POHP2UGCS65TBIUUU, 100000000]]\n",
    events: [
      "AAAAAAAAAAAAAAAAAAAAAgAAAAAAAAADAAAADwAAAAdmbl9jYWxsAAAAAA0AAAAgzXrHlDVNUPOxhsf77xASbfB/2k8LjWHIuCtc+U6tcSwAAAAPAAAAB2V4ZWN1dGUAAAAAEAAAAAEAAAADAAAAEgAAAAHXkotywnA8z+r365/0701QSlWouXn8m0UOoshCtNHOYQAAAA8AAAAIdHJhbnNmZXIAAAAQAAAAAQAAAAMAAAASAAAAAc16x5Q1TVDzsYbH++8QEm3wf9pPC41hyLgrXPlOrXEsAAAAEgAAAAGZH28E7P7H2iQu3i7ds5muWQeGxQ1ET69x36oYUvdmFAAAAAoAAAAAAAAAAAAAAAAF9eEA",
      "AAAAAAAAAAAAAAABzXrHlDVNUPOxhsf77xASbfB/2k8LjWHIuCtc+U6tcSwAAAACAAAAAAAAAAMAAAAPAAAAB2ZuX2NhbGwAAAAADQAAACDXkotywnA8z+r365/0701QSlWouXn8m0UOoshCtNHOYQAAAA8AAAAIdHJhbnNmZXIAAAAQAAAAAQAAAAMAAAASAAAAAc16x5Q1TVDzsYbH++8QEm3wf9pPC41hyLgrXPlOrXEsAAAAEgAAAAGZH28E7P7H2iQu3i7ds5muWQeGxQ1ET69x36oYUvdmFAAAAAoAAAAAAAAAAAAAAAAF9eEA",
      "AAAAAAAAAAAAAAAB15KLcsJwPM/q9+uf9O9NUEpVqLl5/JtFDqLIQrTRzmEAAAACAAAAAAAAAAIAAAAPAAAABWVycm9yAAAAAAAAAgAAAAAAAAAKAAAAEAAAAAEAAAACAAAADgAAACd6ZXJvIGJhbGFuY2UgaXMgbm90IHN1ZmZpY2llbnQgdG8gc3BlbmQAAAAACgAAAAAAAAAAAAAAAAX14QA=",
      "AAAAAAAAAAAAAAABzXrHlDVNUPOxhsf77xASbfB/2k8LjWHIuCtc+U6tcSwAAAACAAAAAAAAAAIAAAAPAAAABWVycm9yAAAAAAAAAgAAAAAAAAAKAAAAEAAAAAEAAAADAAAADgAAABRjb250cmFjdCBjYWxsIGZhaWxlZAAAAA8AAAAIdHJhbnNmZXIAAAAQAAAAAQAAAAMAAAASAAAAAc16x5Q1TVDzsYbH++8QEm3wf9pPC41hyLgrXPlOrXEsAAAAEgAAAAGZH28E7P7H2iQu3i7ds5muWQeGxQ1ET69x36oYUvdmFAAAAAoAAAAAAAAAAAAAAAAF9eEA",
      "AAAAAAAAAAAAAAABzXrHlDVNUPOxhsf77xASbfB/2k8LjWHIuCtc+U6tcSwAAAACAAAAAAAAAAIAAAAPAAAABWVycm9yAAAAAAAAAgAAAAAAAAAKAAAADgAAAEBlc2NhbGF0aW5nIGVycm9yIHRvIFZNIHRyYXAgZnJvbSBmYWlsZWQgaG9zdCBmdW5jdGlvbiBjYWxsOiBjYWxs",
      "AAAAAAAAAAAAAAABzXrHlDVNUPOxhsf77xASbfB/2k8LjWHIuCtc+U6tcSwAAAACAAAAAAAAAAEAAAAPAAAAA2xvZwAAAAAQAAAAAQAAAAMAAAAOAAAAHlZNIGNhbGwgdHJhcHBlZCB3aXRoIEhvc3RFcnJvcgAAAAAADwAAAAdleGVjdXRlAAAAAAIAAAAAAAAACg==",
    ],
    latestLedger: 1933059,
  },
};

const richSubmissionWithoutError = {
  kind: "rpc_simulate" as const,
  transactionXdr:
    "AAAAAgAAAAB+Ey8Dk7Ac+B7nyKes/D7ENuiiiZKyxtxu/60KvssapgACBckAHX8SAAAAAQAAAAEAAAAAAAAAAAAAAABp1o6hAAAAAAAAAAEAAAAAAAAAGAAAAAAAAAAB15KLcsJwPM/q9+uf9O9NUEpVqLl5/JtFDqLIQrTRzmEAAAAIdHJhbnNmZXIAAAADAAAAEgAAAAAAAAAAfhMvA5OwHPge58inrPw+xDbooomSssbcbv+tCr7LGqYAAAASAAAAAc16x5Q1TVDzsYbH++8QEm3wf9pPC41hyLgrXPlOrXEsAAAACgAAAAAAAAAAAAAAF0V794AAAAABAAAAAQAAAAAAAAAAfhMvA5OwHPge58inrPw+xDbooomSssbcbv+tCr7LGqYAAAGdbhyyuwAdgeIAAAAQAAAAAQAAAAEAAAARAAAAAQAAAAIAAAAPAAAACnB1YmxpY19rZXkAAAAAAA0AAAAgfhMvA5OwHPge58inrPw+xDbooomSssbcbv+tCr7LGqYAAAAPAAAACXNpZ25hdHVyZQAAAAAAAA0AAABA+uNNAdrt9q6vTS1eOr52gyAIB+fFYtjYGf0RDDEhJ0aMViZN3nB1TvrqxXkzKP+bi28j81yWI5lzxJz+JQmeCAAAAAAAAAAB15KLcsJwPM/q9+uf9O9NUEpVqLl5/JtFDqLIQrTRzmEAAAAIdHJhbnNmZXIAAAADAAAAEgAAAAAAAAAAfhMvA5OwHPge58inrPw+xDbooomSssbcbv+tCr7LGqYAAAASAAAAAc16x5Q1TVDzsYbH++8QEm3wf9pPC41hyLgrXPlOrXEsAAAACgAAAAAAAAAAAAAAF0V794AAAAAAAAAAAQAAAAAAAAABAAAABgAAAAHXkotywnA8z+r365/0701QSlWouXn8m0UOoshCtNHOYQAAABQAAAABAAAAAgAAAAAAAAAAfhMvA5OwHPge58inrPw+xDbooomSssbcbv+tCr7LGqYAAAAGAAAAAdeSi3LCcDzP6vfrn/TvTVBKVai5efybRQ6iyEK00c5hAAAAEAAAAAEAAAACAAAADwAAAAdCYWxhbmNlAAAAABIAAAABzXrHlDVNUPOxhsf77xASbfB/2k8LjWHIuCtc+U6tcSwAAAABAAP4fQAAAJAAAAFwAAAAAAACBWUAAAABvssapgAAAEDwugdIzt7G/sa667fQYJkFFbSiGJeN2VEBY1pw/FQgod4kNTGCLPEYW3Aw7FZKe3aBN2mdQPbbicLUj+v7n8UO",
  response: {
    latestLedger: 1933075,
    latestLedgerCloseTime: "1775668870",
    status: "FAILED",
    txHash: "5a5b4e6ec93564c581cd8bb6ff43adccb4cf6e98b4853facbe7ecaab49667877",
    resultXdr: "AAAAAAAAMTj/////AAAAAQAAAAAAAAAY/////QAAAAA=",
    resultMetaXdr:
      "AAAABAAAAAAAAAACAAAAAwAdfxMAAAAAAAAAAH4TLwOTsBz4HufIp6z8PsQ26KKJkrLG3G7/rQq+yxqmAAAAF0h04jcAHX8SAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAQAdfxMAAAAAAAAAAH4TLwOTsBz4HufIp6z8PsQ26KKJkrLG3G7/rQq+yxqmAAAAF0h04jcAHX8SAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAB1/EwAAAABp1o6GAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAMNQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAHXkotywnA8z+r365/0701QSlWouXn8m0UOoshCtNHOYQAAAAEAAAAAAAAAAgAAAA8AAAADZmVlAAAAABIAAAAAAAAAAH4TLwOTsBz4HufIp6z8PsQ26KKJkrLG3G7/rQq+yxqmAAAACgAAAAAAAAAAAAAAAAACBckAAAACAAAAAAAAAAHXkotywnA8z+r365/0701QSlWouXn8m0UOoshCtNHOYQAAAAEAAAAAAAAAAgAAAA8AAAADZmVlAAAAABIAAAAAAAAAAH4TLwOTsBz4HufIp6z8PsQ26KKJkrLG3G7/rQq+yxqmAAAACv/////////////////+K28AAAAWAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAADAAAADwAAAAdmbl9jYWxsAAAAAA0AAAAg15KLcsJwPM/q9+uf9O9NUEpVqLl5/JtFDqLIQrTRzmEAAAAPAAAACHRyYW5zZmVyAAAAEAAAAAEAAAADAAAAEgAAAAAAAAAAfhMvA5OwHPge58inrPw+xDbooomSssbcbv+tCr7LGqYAAAASAAAAAc16x5Q1TVDzsYbH++8QEm3wf9pPC41hyLgrXPlOrXEsAAAACgAAAAAAAAAAAAAAF0V794AAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAPAAAADmhvc3RfZm5fZmFpbGVkAAAAAAACAAAABwAAAAUAAAABAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAADwAAAAVlcnJvcgAAAAAAAAIAAAAHAAAABQAAABAAAAABAAAAAwAAAA4AAAAvb3BlcmF0aW9uIGluc3RydWN0aW9ucyBleGNlZWRzIGFtb3VudCBzcGVjaWZpZWQAAAAABQAAAAAACEijAAAABQAAAAAAA/h9AAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAADwAAAAxjb3JlX21ldHJpY3MAAAAPAAAACnJlYWRfZW50cnkAAAAAAAUAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAA8AAAAMY29yZV9tZXRyaWNzAAAADwAAAAt3cml0ZV9lbnRyeQAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAPAAAADGNvcmVfbWV0cmljcwAAAA8AAAAQbGVkZ2VyX3JlYWRfYnl0ZQAAAAUAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAA8AAAAMY29yZV9tZXRyaWNzAAAADwAAABFsZWRnZXJfd3JpdGVfYnl0ZQAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAA8AAAAMY29yZV9tZXRyaWNzAAAADwAAAA1yZWFkX2tleV9ieXRlAAAAAAAABQAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAADwAAAAxjb3JlX21ldHJpY3MAAAAPAAAADndyaXRlX2tleV9ieXRlAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAPAAAADGNvcmVfbWV0cmljcwAAAA8AAAAOcmVhZF9kYXRhX2J5dGUAAAAAAAUAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAA8AAAAMY29yZV9tZXRyaWNzAAAADwAAAA93cml0ZV9kYXRhX2J5dGUAAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAADwAAAAxjb3JlX21ldHJpY3MAAAAPAAAADnJlYWRfY29kZV9ieXRlAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAPAAAADGNvcmVfbWV0cmljcwAAAA8AAAAPd3JpdGVfY29kZV9ieXRlAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAA8AAAAMY29yZV9tZXRyaWNzAAAADwAAAAplbWl0X2V2ZW50AAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAPAAAADGNvcmVfbWV0cmljcwAAAA8AAAAPZW1pdF9ldmVudF9ieXRlAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAA8AAAAMY29yZV9tZXRyaWNzAAAADwAAAAhjcHVfaW5zbgAAAAUAAAAAAAhIowAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAA8AAAAMY29yZV9tZXRyaWNzAAAADwAAAAhtZW1fYnl0ZQAAAAUAAAAAAABD4QAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAA8AAAAMY29yZV9tZXRyaWNzAAAADwAAABFpbnZva2VfdGltZV9uc2VjcwAAAAAAAAUAAAAAAAFtjQAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAA8AAAAMY29yZV9tZXRyaWNzAAAADwAAAA9tYXhfcndfa2V5X2J5dGUAAAAABQAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAADwAAAAxjb3JlX21ldHJpY3MAAAAPAAAAEG1heF9yd19kYXRhX2J5dGUAAAAFAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAPAAAADGNvcmVfbWV0cmljcwAAAA8AAAAQbWF4X3J3X2NvZGVfYnl0ZQAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAgAAAA8AAAAMY29yZV9tZXRyaWNzAAAADwAAABNtYXhfZW1pdF9ldmVudF9ieXRlAAAAAAUAAAAAAAAAAA==",
    diagnosticEventsXdr: [
      "AAAAAAAAAAAAAAAAAAAAAgAAAAAAAAADAAAADwAAAAdmbl9jYWxsAAAAAA0AAAAg15KLcsJwPM/q9+uf9O9NUEpVqLl5/JtFDqLIQrTRzmEAAAAPAAAACHRyYW5zZmVyAAAAEAAAAAEAAAADAAAAEgAAAAAAAAAAfhMvA5OwHPge58inrPw+xDbooomSssbcbv+tCr7LGqYAAAASAAAAAc16x5Q1TVDzsYbH++8QEm3wf9pPC41hyLgrXPlOrXEsAAAACgAAAAAAAAAAAAAAF0V794A=",
      "AAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAADwAAAA5ob3N0X2ZuX2ZhaWxlZAAAAAAAAgAAAAcAAAAFAAAAAQ==",
      "AAAAAAAAAAAAAAAAAAAAAgAAAAAAAAACAAAADwAAAAVlcnJvcgAAAAAAAAIAAAAHAAAABQAAABAAAAABAAAAAwAAAA4AAAAvb3BlcmF0aW9uIGluc3RydWN0aW9ucyBleGNlZWRzIGFtb3VudCBzcGVjaWZpZWQAAAAABQAAAAAACEijAAAABQAAAAAAA/h9",
    ],
    createdAt: "1775668870",
    ledger: 1933075,
  },
};

describe("direct error normalization with rich simulation payload", () => {
  it("preserves the full error while extracting structured Soroban metadata", async () => {
    const tx = await buildFailedTransactionFromDirectError(submission);

    expect(tx.observationKind).toBe("rpc_simulate");
    expect(tx.ledgerSequence).toBe(1933059);
    expect(tx.resultKind).toBe("simulate:hosterror_error_contract_10");
    expect(tx.primaryContractIds).toEqual([
      "CDGXVR4UGVGVB45RQ3D7X3YQCJW7A762J4FY2YOIXAVVZ6KOVVYSYBX5",
    ]);
    expect(tx.contractIds).toEqual(expect.arrayContaining([
      "CDGXVR4UGVGVB45RQ3D7X3YQCJW7A762J4FY2YOIXAVVZ6KOVVYSYBX5",
      "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
    ]));
    expect(tx.operationTypes).toEqual(["invoke_host_function"]);
    expect(tx.sorobanOperationTypes).toEqual(["invoke_host_function"]);
    expect(tx.decoded.topLevelFunction).toBe("execute");
    expect(tx.decoded.invokeCalls).toEqual([
      expect.objectContaining({
        contractId: "CDGXVR4UGVGVB45RQ3D7X3YQCJW7A762J4FY2YOIXAVVZ6KOVVYSYBX5",
        functionName: "execute",
      }),
    ]);
    expect(tx.decoded.errorSignatures).toContainEqual({
      type: "contract",
      code: "10",
    });
    expect(tx.readout.invokeCallCount).toBe(1);
    expect(tx.readout.contractCount).toBe(3);
    expect(tx.readout.diagnosticEventCount).toBe(6);
    expect(tx.readout.simulationError).toContain(
      "zero balance is not sufficient to spend",
    );
  });

  it("normalizes rich FAILED simulation payloads when the RPC omits response.error", async () => {
    const tx = await buildFailedTransactionFromDirectError(
      richSubmissionWithoutError,
    );

    expect(tx.observationKind).toBe("rpc_simulate");
    expect(tx.txHash).toBe(
      "5a5b4e6ec93564c581cd8bb6ff43adccb4cf6e98b4853facbe7ecaab49667877",
    );
    expect(tx.resultKind).toBe("simulate:tx_failed");
    expect(tx.ledgerSequence).toBe(1933075);
    expect(tx.ledgerCloseTime).toBe("2026-04-08T17:21:10.000Z");
    expect(tx.readout.simulationError).toContain(
      "operation instructions exceeds amount specified",
    );
    expect(tx.readout.diagnosticEventCount).toBe(3);
  });
});
